<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class Updatert_kesehatanRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, mixed>
     */
    public function rules()
    {
        return [

            'valnama_rs' => 'nullable',
            'valpemilik_rs' => 'nullable',
            'valjd_rs' => 'nullable',
            'valjb_rs' => 'nullable',
            'valjts_rs' => 'nullable',
            'valjp_rs' => 'nullable',
            'valnama_rsb' => 'nullable',
            'valpemilik_rsb' => 'nullable',
            'valjd_rsb' => 'nullable',
            'valjb_rsb' => 'nullable',
            'valjts_rsb' => 'nullable',
            'valjp_rsb' => 'nullable',
            'valnama_pdri' => 'nullable',
            'valpemilik_pdri' => 'nullable',
            'valjd_pdri' => 'nullable',
            'valjb_pdri' => 'nullable',
            'valjts_pdri' => 'nullable',
            'valjp_pdri' => 'nullable',
            'valnama_ptri' => 'nullable',
            'valpemilik_ptri' => 'nullable',
            'valjd_ptri' => 'nullable',
            'valjb_ptri' => 'nullable',
            'valjts_ptri' => 'nullable',
            'valjp_ptri' => 'nullable',
            'valnama_pp' => 'nullable',
            'valpemilik_pp' => 'nullable',
            'valjd_pp' => 'nullable',
            'valjb_pp' => 'nullable',
            'valjts_pp' => 'nullable',
            'valjp_pp' => 'nullable',
            'valnama_pbp' => 'nullable',
            'valpemilik_pbp' => 'nullable',
            'valjd_pbp' => 'nullable',
            'valjb_pbp' => 'nullable',
            'valjts_pbp' => 'nullable',
            'valjp_pbp' => 'nullable',
            'valnama_tpd' => 'nullable',
            'valpemilik_tpd' => 'nullable',
            'valjd_tpd' => 'nullable',
            'valjb_tpd' => 'nullable',
            'valjts_tpd' => 'nullable',
            'valjp_tpd' => 'nullable',
            'valnama_rb' => 'nullable',
            'valpemilik_rb' => 'nullable',
            'valjd_rb' => 'nullable',
            'valjb_rb' => 'nullable',
            'valjts_rb' => 'nullable',
            'valjp_rb' => 'nullable',
            'valnama_tpb' => 'nullable',
            'valpemilik_tpb' => 'nullable',
            'valjd_tpb' => 'nullable',
            'valjb_tpb' => 'nullable',
            'valjts_tpb' => 'nullable',
            'valjp_tpb' => 'nullable',
            'valnama_poskedes' => 'nullable',
            'valpemilik_poskedes' => 'nullable',
            'valjd_poskedes' => 'nullable',
            'valjb_poskedes' => 'nullable',
            'valjts_poskedes' => 'nullable',
            'valjp_poskedes' => 'nullable',
            'valnama_polindes' => 'nullable',
            'valpemilik_polindes' => 'nullable',
            'valjd_polindes' => 'nullable',
            'valjb_polindes' => 'nullable',
            'valjts_polindes' => 'nullable',
            'valjp_polindes' => 'nullable',
            'valnama_apotik' => 'nullable',
            'valpemilik_apotik' => 'nullable',
            'valjd_apotik' => 'nullable',
            'valjb_apotik' => 'nullable',
            'valjts_apotik' => 'nullable',
            'valjp_apotik' => 'nullable',
            'valnama_tokojamu' => 'nullable',
            'valpemilik_tokojamu' => 'nullable',
            'valjd_tokojamu' => 'nullable',
            'valjb_tokojamu' => 'nullable',
            'valjts_tokojamu' => 'nullable',
            'valjp_tokojamu' => 'nullable',
            'valnama_posyandu' => 'nullable',
            'valpemilik_posyandu' => 'nullable',
            'valjd_posyandu' => 'nullable',
            'valjb_posyandu' => 'nullable',
            'valjts_posyandu' => 'nullable',
            'valjp_posyandu' => 'nullable',
            'valnama_posbindu' => 'nullable',
            'valpemilik_posbindu' => 'nullable',
            'valjd_posbindu' => 'nullable',
            'valjb_posbindu' => 'nullable',
            'valjts_posbindu' => 'nullable',
            'valjp_posbindu' => 'nullable',
            'valnama_tpd' => 'nullable',
            'valpemilik_tpd' => 'nullable',
            'valjd_tpd' => 'nullable',
            'valjb_tpd' => 'nullable',
            'valjts_tpd' => 'nullable',
            'valjp_tpd' => 'nullable',


        ];
    }

    public function messages(): array
    {
        return [
            'valnama_rs.required' => ':Attribute tidak boleh kosong',
            'valpemilik_rs.required' => ':Attribute tidak boleh kosong',
            'valjd_rs.required' => ':Attribute tidak boleh kosong',
            'valjb_rs.required' => ':Attribute tidak boleh kosong',
            'valjts_rs.required' => ':Attribute tidak boleh kosong',
            'valjp_rs.required' => ':Attribute tidak boleh kosong',
            'valnama_rsb.required' => ':Attribute tidak boleh kosong',
            'valpemilik_rsb.required' => ':Attribute tidak boleh kosong',
            'valjd_rsb.required' => ':Attribute tidak boleh kosong',
            'valjb_rsb.required' => ':Attribute tidak boleh kosong',
            'valjts_rsb.required' => ':Attribute tidak boleh kosong',
            'valjp_rsb.required' => ':Attribute tidak boleh kosong',
            'valnama_pdri.required' => ':Attribute tidak boleh kosong',
            'valpemilik_pdri.required' => ':Attribute tidak boleh kosong',
            'valjd_pdri.required' => ':Attribute tidak boleh kosong',
            'valjb_pdri.required' => ':Attribute tidak boleh kosong',
            'valjts_pdri.required' => ':Attribute tidak boleh kosong',
            'valjp_pdri.required' => ':Attribute tidak boleh kosong',
            'valnama_ptri.required' => ':Attribute tidak boleh kosong',
            'valpemilik_ptri.required' => ':Attribute tidak boleh kosong',
            'valjd_ptri.required' => ':Attribute tidak boleh kosong',
            'valjb_ptri.required' => ':Attribute tidak boleh kosong',
            'valjts_ptri.required' => ':Attribute tidak boleh kosong',
            'valjp_ptri.required' => ':Attribute tidak boleh kosong',
            'valnama_pp.required' => ':Attribute tidak boleh kosong',
            'valpemilik_pp.required' => ':Attribute tidak boleh kosong',
            'valjd_pp.required' => ':Attribute tidak boleh kosong',
            'valjb_pp.required' => ':Attribute tidak boleh kosong',
            'valjts_pp.required' => ':Attribute tidak boleh kosong',
            'valjp_pp.required' => ':Attribute tidak boleh kosong',
            'valnama_pbp.required' => ':Attribute tidak boleh kosong',
            'valpemilik_pbp.required' => ':Attribute tidak boleh kosong',
            'valjd_pbp.required' => ':Attribute tidak boleh kosong',
            'valjb_pbp.required' => ':Attribute tidak boleh kosong',
            'valjts_pbp.required' => ':Attribute tidak boleh kosong',
            'valjp_pbp.required' => ':Attribute tidak boleh kosong',
            'valnama_tpd.required' => ':Attribute tidak boleh kosong',
            'valpemilik_tpd.required' => ':Attribute tidak boleh kosong',
            'valjd_tpd.required' => ':Attribute tidak boleh kosong',
            'valjb_tpd.required' => ':Attribute tidak boleh kosong',
            'valjts_tpd.required' => ':Attribute tidak boleh kosong',
            'valjp_tpd.required' => ':Attribute tidak boleh kosong',
            'valnama_rb.required' => ':Attribute tidak boleh kosong',
            'valpemilik_rb.required' => ':Attribute tidak boleh kosong',
            'valjd_rb.required' => ':Attribute tidak boleh kosong',
            'valjb_rb.required' => ':Attribute tidak boleh kosong',
            'valjts_rb.required' => ':Attribute tidak boleh kosong',
            'valjp_rb.required' => ':Attribute tidak boleh kosong',
            'valnama_tpb.required' => ':Attribute tidak boleh kosong',
            'valpemilik_tpb.required' => ':Attribute tidak boleh kosong',
            'valjd_tpb.required' => ':Attribute tidak boleh kosong',
            'valjb_tpb.required' => ':Attribute tidak boleh kosong',
            'valjts_tpb.required' => ':Attribute tidak boleh kosong',
            'valjp_tpb.required' => ':Attribute tidak boleh kosong',
            'valnama_poskedes.required' => ':Attribute tidak boleh kosong',
            'valpemilik_poskedes.required' => ':Attribute tidak boleh kosong',
            'valjd_poskedes.required' => ':Attribute tidak boleh kosong',
            'valjb_poskedes.required' => ':Attribute tidak boleh kosong',
            'valjts_poskedes.required' => ':Attribute tidak boleh kosong',
            'valjp_poskedes.required' => ':Attribute tidak boleh kosong',
            'valnama_polindes.required' => ':Attribute tidak boleh kosong',
            'valpemilik_polindes.required' => ':Attribute tidak boleh kosong',
            'valjd_polindes.required' => ':Attribute tidak boleh kosong',
            'valjb_polindes.required' => ':Attribute tidak boleh kosong',
            'valjts_polindes.required' => ':Attribute tidak boleh kosong',
            'valjp_polindes.required' => ':Attribute tidak boleh kosong',
            'valnama_apotik.required' => ':Attribute tidak boleh kosong',
            'valpemilik_apotik.required' => ':Attribute tidak boleh kosong',
            'valjd_apotik.required' => ':Attribute tidak boleh kosong',
            'valjb_apotik.required' => ':Attribute tidak boleh kosong',
            'valjts_apotik.required' => ':Attribute tidak boleh kosong',
            'valjp_apotik.required' => ':Attribute tidak boleh kosong',
            'valnama_tokojamu.required' => ':Attribute tidak boleh kosong',
            'valpemilik_tokojamu.required' => ':Attribute tidak boleh kosong',
            'valjd_tokojamu.required' => ':Attribute tidak boleh kosong',
            'valjb_tokojamu.required' => ':Attribute tidak boleh kosong',
            'valjts_tokojamu.required' => ':Attribute tidak boleh kosong',
            'valjp_tokojamu.required' => ':Attribute tidak boleh kosong',
            'valnama_posyandu.required' => ':Attribute tidak boleh kosong',
            'valpemilik_posyandu.required' => ':Attribute tidak boleh kosong',
            'valjd_posyandu.required' => ':Attribute tidak boleh kosong',
            'valjb_posyandu.required' => ':Attribute tidak boleh kosong',
            'valjts_posyandu.required' => ':Attribute tidak boleh kosong',
            'valjp_posyandu.required' => ':Attribute tidak boleh kosong',
            'valnama_posbindu.required' => ':Attribute tidak boleh kosong',
            'valpemilik_posbindu.required' => ':Attribute tidak boleh kosong',
            'valjd_posbindu.required' => ':Attribute tidak boleh kosong',
            'valjb_posbindu.required' => ':Attribute tidak boleh kosong',
            'valjts_posbindu.required' => ':Attribute tidak boleh kosong',
            'valjp_posbindu.required' => ':Attribute tidak boleh kosong',
            'valnama_tpd.required' => ':Attribute tidak boleh kosong',
            'valpemilik_tpd.required' => ':Attribute tidak boleh kosong',
            'valjd_tpd.required' => ':Attribute tidak boleh kosong',
            'valjb_tpd.required' => ':Attribute tidak boleh kosong',
            'valjts_tpd.required' => ':Attribute tidak boleh kosong',
            'valjp_tpd.required' => ':Attribute tidak boleh kosong',




        ];
    }

    public function attributes(): array
    {
        return [

            'valnama_rs' => 'nama_rs',
            'valpemilik_rs' => 'pemilik_rs',
            'valjd_rs' => 'jd_rs',
            'valjb_rs' => 'jb_rs',
            'valjts_rs' => 'jts_rs',
            'valjp_rs' => 'jp_rs',
            'valnama_rsb' => 'nama_rsb',
            'valpemilik_rsb' => 'pemilik_rsb',
            'valjd_rsb' => 'jd_rsb',
            'valjb_rsb' => 'jb_rsb',
            'valjts_rsb' => 'jts_rsb',
            'valjp_rsb' => 'jp_rsb',
            'valnama_pdri' => 'nama_pdri',
            'valpemilik_pdri' => 'pemilik_pdri',
            'valjd_pdri' => 'jd_pdri',
            'valjb_pdri' => 'jb_pdri',
            'valjts_pdri' => 'jts_pdri',
            'valjp_pdri' => 'jp_pdri',
            'valnama_ptri' => 'nama_ptri',
            'valpemilik_ptri' => 'pemilik_ptri',
            'valjd_ptri' => 'jd_ptri',
            'valjb_ptri' => 'jb_ptri',
            'valjts_ptri' => 'jts_ptri',
            'valjp_ptri' => 'jp_ptri',
            'valnama_pp' => 'nama_pp',
            'valpemilik_pp' => 'pemilik_pp',
            'valjd_pp' => 'jd_pp',
            'valjb_pp' => 'jb_pp',
            'valjts_pp' => 'jts_pp',
            'valjp_pp' => 'jp_pp',
            'valnama_pbp' => 'nama_pbp',
            'valpemilik_pbp' => 'pemilik_pbp',
            'valjd_pbp' => 'jd_pbp',
            'valjb_pbp' => 'jb_pbp',
            'valjts_pbp' => 'jts_pbp',
            'valjp_pbp' => 'jp_pbp',
            'valnama_tpd' => 'nama_tpd',
            'valpemilik_tpd' => 'pemilik_tpd',
            'valjd_tpd' => 'jd_tpd',
            'valjb_tpd' => 'jb_tpd',
            'valjts_tpd' => 'jts_tpd',
            'valjp_tpd' => 'jp_tpd',
            'valnama_rb' => 'nama_rb',
            'valpemilik_rb' => 'pemilik_rb',
            'valjd_rb' => 'jd_rb',
            'valjb_rb' => 'jb_rb',
            'valjts_rb' => 'jts_rb',
            'valjp_rb' => 'jp_rb',
            'valnama_tpb' => 'nama_tpb',
            'valpemilik_tpb' => 'pemilik_tpb',
            'valjd_tpb' => 'jd_tpb',
            'valjb_tpb' => 'jb_tpb',
            'valjts_tpb' => 'jts_tpb',
            'valjp_tpb' => 'jp_tpb',
            'valnama_poskedes' => 'nama_poskedes',
            'valpemilik_poskedes' => 'pemilik_poskedes',
            'valjd_poskedes' => 'jd_poskedes',
            'valjb_poskedes' => 'jb_poskedes',
            'valjts_poskedes' => 'jts_poskedes',
            'valjp_poskedes' => 'jp_poskedes',
            'valnama_polindes' => 'nama_polindes',
            'valpemilik_polindes' => 'pemilik_polindes',
            'valjd_polindes' => 'jd_polindes',
            'valjb_polindes' => 'jb_polindes',
            'valjts_polindes' => 'jts_polindes',
            'valjp_polindes' => 'jp_polindes',
            'valnama_apotik' => 'nama_apotik',
            'valpemilik_apotik' => 'pemilik_apotik',
            'valjd_apotik' => 'jd_apotik',
            'valjb_apotik' => 'jb_apotik',
            'valjts_apotik' => 'jts_apotik',
            'valjp_apotik' => 'jp_apotik',
            'valnama_tokojamu' => 'nama_tokojamu',
            'valpemilik_tokojamu' => 'pemilik_tokojamu',
            'valjd_tokojamu' => 'jd_tokojamu',
            'valjb_tokojamu' => 'jb_tokojamu',
            'valjts_tokojamu' => 'jts_tokojamu',
            'valjp_tokojamu' => 'jp_tokojamu',
            'valnama_posyandu' => 'nama_posyandu',
            'valpemilik_posyandu' => 'pemilik_posyandu',
            'valjd_posyandu' => 'jd_posyandu',
            'valjb_posyandu' => 'jb_posyandu',
            'valjts_posyandu' => 'jts_posyandu',
            'valjp_posyandu' => 'jp_posyandu',
            'valnama_posbindu' => 'nama_posbindu',
            'valpemilik_posbindu' => 'pemilik_posbindu',
            'valjd_posbindu' => 'jd_posbindu',
            'valjb_posbindu' => 'jb_posbindu',
            'valjts_posbindu' => 'jts_posbindu',
            'valjp_posbindu' => 'jp_posbindu',
            'valnama_tpd' => 'nama_tpd',
            'valpemilik_tpd' => 'pemilik_tpd',
            'valjd_tpd' => 'jd_tpd',
            'valjb_tpd' => 'jb_tpd',
            'valjts_tpd' => 'jts_tpd',
            'valjp_tpd' => 'jp_tpd',



        ];
    }
}
