<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\Relations\HasOne;
use Jenssegers\Mongodb\Eloquent\Model as Eloquent;

class rt_sarana_ekonomi extends Eloquent
{
    protected $connection = 'mongodb';
    protected $collection = 'rt_sarana_ekonomi';
    protected $fillable = [        
        'jumlah_toko',	
        'kondisi_toko',	
        'Jarak_toko',	
        'kemudahan_toko',
        'jumlah_pasar_permanen',	
        'kondisi_pasar_permanen',	
        'Jarak_pasar_permanen',	
        'kemudahan_pasar_permanen',
        'jumlah_semip',	
        'kondisi_semip',	
        'Jarak_semip',	
        'kemudahan_semip',
        'jumlah_tanpap',	
        'kondisi_tanpap',	
        'Jarak_tanpap',	
        'kemudahan_tanpap',
        'jumlah_minimarket',	
        'kondisi_minimarket',	
        'Jarak_minimarket',	
        'kemudahan_minimarket',
        'jumlah_warungk',	
        'kondisi_warungk',	
        'Jarak_warungk',	
        'kemudahan_warungk',
        'jumlah_warungp',	
        'kondisi_warungp',	
        'Jarak_warungp',	
        'kemudahan_warungp',
        'jumlah_restoran',	
        'kondisi_restoran',	
        'Jarak_restoran',	
        'kemudahan_restoran',
        'jumlah_kedaim',	
        'kondisi_kedaim',	
        'Jarak_kedaim',	
        'kemudahan_kedaim',
        'jumlah_hotel',	
        'kondisi_hotel',	
        'Jarak_hotel',	
        'kemudahan_hotel',
        'jumlah_hostel',	
        'kondisi_hostel',	
        'Jarak_hostel',	
        'kemudahan_hostel',
        'jumlah_bengkelm',	
        'kondisi_bengkelm',	
        'Jarak_bengkelm',	
        'kemudahan_bengkelm',
        'jumlah_salonk',	
        'kondisi_salonk',	
        'Jarak_salonk',	
        'kemudahan_salonk',
        'jumlah_agent',	
        'kondisi_agent',	
        'Jarak_agent',	
        'kemudahan_agent',
        'jumlah_bankbri',	
        'kondisi_bankbri',	
        'Jarak_bankbri',	
        'kemudahan_bankbri',
        'jumlah_briag',	
        'kondisi_briag',	
        'Jarak_briag',	
        'kemudahan_briag',
        'jumlah_bankbni',	
        'kondisi_bankbni',	
        'Jarak_bankbni',	
        'kemudahan_bankbni',
        'jumlah_bniag',	
        'kondisi_bniag',	
        'Jarak_bniag',	
        'kemudahan_bniag',
        'jumlah_bankmandiri',	
        'kondisi_bankmandiri',	
        'Jarak_bankmandiri',	
        'kemudahan_bankmandiri',
        'jumlah_mandiriag',	
        'kondisi_mandiriag',	
        'Jarak_mandiriag',	
        'kemudahan_mandiriag',
        'jumlah_bankbpd',	
        'kondisi_bankbpd',	
        'Jarak_bankbpd',	
        'kemudahan_bankbpd',
        'jumlah_bpdag',	
        'kondisi_bpdag',	
        'Jarak_bpdag',	
        'kemudahan_bpdag',
        'jumlah_bankumum',	
        'kondisi_bankumum',	
        'Jarak_bankumum',	
        'kemudahan_bankumum',
        'jumlah_bankbca',	
        'kondisi_bankbca',	
        'Jarak_bankbca',	
        'kemudahan_bankbca',
        'jumlah_bankcimb',	
        'kondisi_bankcimb',	
        'Jarak_bankcimb',	
        'kemudahan_bankcimb',
        'jumlah_banksinarm',	
        'kondisi_banksinarm',	
        'Jarak_banksinarm',	
        'kemudahan_banksinarm',
        'jumlah_bankpermata',	
        'kondisi_bankpermata',	
        'Jarak_bankpermata',	
        'kemudahan_bankpermata',
        'jumlah_bankswastalain',	
        'kondisi_bankswastalain',	
        'Jarak_bankswastalain',	
        'kemudahan_bankswastalain',
        'jumlah_bankbpr',	
        'kondisi_bankbpr',	
        'Jarak_bankbpr',	
        'kemudahan_bankbpr',
        'jumlah_bmt',	
        'kondisi_bmt',	
        'Jarak_bmt',	
        'kemudahan_bmt',
        'jumlah_pegadaian',	
        'kondisi_pegadaian',	
        'Jarak_pegadaian',	
        'kemudahan_pegadaian',
        'jumlah_atm',	
        'kondisi_atm',	
        'Jarak_atm',	
        'kemudahan_atm',
        'jumlah_saranalain',	
        'kondisi_saranalain',	
        'Jarak_saranalain',	
        'kemudahan_saranalain',       
        
    ];
}
